name: "Boost Security Scanner"
description: "Scans a repository for security vulneratibilities"
inputs:
  additional_args:
    description: "Additional CLI arguments to pass"
    required: false
    default: ""
  api_enabled:
    description: "Optional setting to enable offline mode"
    default: true
  api_endpoint:
    description: "Boost API endpoint"
    required: true
    default: https://api.boostsecurity.io
  api_token:
    description: "Boost API token"
    required: true
  cli_version:
    description: "Scanner version"
    default: "1"
  ignore_failure:
    description: "Ignore any exception returned by the scanner cli"
    default: "false"
  log_level:
    description: "Set the cli logging level"
    default: ""
  main_branch:
    description: "Optional override for main branch detection"
    default: ""
  pre_scan_cmd:
    description: "Optional command to run before scanning"
    default: ""
  registry_module:
    description: "Module within the scanner registry to execute"
    required: true
  scanner_id:
    description: "Optional identifier to uniquely identify the scanner"
    default: ""
  scan_label:
    description: "Optional identifier to identify a a monorepo component"
    default: ""
  scan_path:
    description: "Optional relative path to scan"
    default: ""
  scan_timeout:
    description: "Maximum amount of time a diff scan should complete in (deprecated)"
    default: ""
  scan_diff_timeout:
    description: "Maximum amount of time a diff scan should complete in"
    default: ""
  scan_main_timeout:
    description: "Maximum amount of time a main scan should complete in"
    default: ""
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/lib/scan.sh
      shell: bash
      env:
        BOOST_API_ENABLED: ${{ inputs.api_enabled }}
        BOOST_API_ENDPOINT: ${{ inputs.api_endpoint }}
        BOOST_API_TOKEN: ${{ inputs.api_token }}
        BOOST_CLI_ARGUMENTS: ${{ inputs.additional_args }}
        BOOST_CLI_VERSION: ${{ inputs.cli_version }}
        BOOST_GIT_MAIN_BRANCH: ${{ inputs.main_branch }}
        BOOST_IGNORE_FAILURE: ${{ inputs.ignore_failure }}
        BOOST_LOG_LEVEL: ${{ inputs.log_level }}
        BOOST_SCAN_TIMEOUT: ${{ inputs.scan_timeout }}
        BOOST_DIFF_SCAN_TIMEOUT: ${{ inputs.scan_diff_timeout }}
        BOOST_MAIN_SCAN_TIMEOUT: ${{ inputs.scan_main_timeout }}
        BOOST_PRE_SCAN: ${{ inputs.pre_scan_cmd }}
        BOOST_SCAN_LABEL: ${{ inputs.scan_label }}
        BOOST_SCAN_PATH: ${{ inputs.scan_path }}
        BOOST_SCANNER_ID: ${{ inputs.scanner_id }}
        BOOST_SCANNER_REGISTRY_MODULE: ${{ inputs.registry_module }}
