name: "Boost Security Scanner"
description: "Scans a repository for security vulneratibilities"
inputs:
  action:
    description: "Action to perform, one of: exec, scan"
    required: true
    default: scan
  additional_args:
    description: "Additional CLI arguments to pass"
    required: false
    default: ""
  api_endpoint:
    description: "Boost API endpoint"
    required: true
    default: https://api.boostsecurity.net
  api_token:
    description: "Boost API token"
    required: true
  cli_version:
    description: "Scanner version"
    default: "3.0"
  exec_command:
    description: "Command to run when in exec mode"
    default: ""
  scanner_image:
    description: "Scanner docker image url"
    default: ""
  scanner_version:
    description: "Scanner docker image tag"
    default: ""
  step_name:
    description: "Identifier for this scanner step"
    default: ""
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/scan.sh
      shell: bash
      env:
        BOOST_API_ENDPOINT: ${{ inputs.api_endpoint }}
        BOOST_API_TOKEN: ${{ inputs.api_token }}
        BOOST_CLI_ARGUMENTS: ${{ inputs.additional_args }}
        BOOST_CLI_VERSION: ${{ inputs.cli_version }}
        BOOST_SCANNER_IMAGE: ${{ inputs.scanner_image }}
        BOOST_SCANNER_VERSION: ${{ inputs.scanner_version }}
        BOOST_STEP_NAME: ${{ inputs.step_name }}
        INPUT_ACTION: ${{ inputs.action }}
        INPUT_EXEC_COMMAND: ${{ inputs.exec_command }}
