name: SAST
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  boost_security_sast:
    name: Boost Security Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Native Scanner
        uses: boostsecurityio/boostsec-scanner-github@v3
        with:
          action: scan
          api_token: ${{ secrets.BOOST_API_TOKEN }}
