name: SBOM
on:
  push:
    branches:
      - main
jobs:
  sbom:
    name: Generate and store artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
